#!/usr/bin/env python

# Copyright (C) <2015> EMBL-European Bioinformatics Institute

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# Neither the institution name nor the name seer_pipeline can
# be used to endorse or promote products derived from this
# software without prior written permission. For written
# permission, please contact <marco@ebi.ac.uk>.

# Products derived from this software may not be called
# seer_pipeline nor may seer_pipeline appear in their names
# without prior written permission of the developers.
# You should have received a copy of the GNU General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.

if __name__ == '__main__':
    import os
    import sys
    import pandas as pd

    d = {}
    for l in sys.stdin:
        genome1, genome2, distance = l.rstrip().split('\t')[:3]

        genome1 = os.path.split(genome1)[-1].split('_')[0]
        genome2 = os.path.split(genome2)[-1].split('_')[0]

        d[genome1] = d.get(genome1, {})
        d[genome1][genome2] = distance
        d[genome2] = d.get(genome2, {})
        d[genome2][genome1] = distance

    m = pd.DataFrame(d)
    m = m.loc[sorted(m.index),
              sorted(m.columns)]
    m.to_csv(sys.stdout, sep=',',
             index=False,
             header=False)
